// <auto-generated />
namespace wall_e_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addcreatemigrationuserinfoandaccountinfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcreatemigrationuserinfoandaccountinfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201806190421033_add create migration userinfo and accountinfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
